buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Updated to a more recent version
        classpath 'com.google.gms:google-services:4.4.2'
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    // Updated to a more recent version
    id 'com.android.application' version '8.4.2' apply false
}
