{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.4.1.jar",
          "url": "builder-8.4.1.jar",
          "size": 13420595,
          "sha512": "ab61e5a2bd6efb828b412bdf293cb3a1308c03fb81adf9b9e15ac67467aa53377a5abd44277e039ca4dcdef0859cea5384cd23c0f8fb40385395fe8c1e092f9d",
          "sha256": "27f8cd73e0ad60c2276c5d4e3c95d6f003fd02edd182ed77692dbbd13947449c",
          "sha1": "adf97221372045e09814894e53c48c7defc5fc16",
          "md5": "f6463c43c237c1aacb32f0543ab8368d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.4.1.jar",
          "url": "builder-8.4.1.jar",
          "size": 13420595,
          "sha512": "ab61e5a2bd6efb828b412bdf293cb3a1308c03fb81adf9b9e15ac67467aa53377a5abd44277e039ca4dcdef0859cea5384cd23c0f8fb40385395fe8c1e092f9d",
          "sha256": "27f8cd73e0ad60c2276c5d4e3c95d6f003fd02edd182ed77692dbbd13947449c",
          "sha1": "adf97221372045e09814894e53c48c7defc5fc16",
          "md5": "f6463c43c237c1aacb32f0543ab8368d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.4.1-javadoc.jar",
          "url": "builder-8.4.1-javadoc.jar",
          "size": 401060,
          "sha512": "bee9b1b3ecc479f33536d1bdc5f5076b2e67e82f81e4d2a1728ead43652e05b68a2208fce0b1b80775871b413ed559ff012152a9d366a2dbe0840a122d8a0e39",
          "sha256": "8c292383a12cbf5c1b4477f5b1204fbcfd76e505f353f90ce722acac5a0615e3",
          "sha1": "c22cc2a2a684ce14a266ec81bc05357467b73985",
          "md5": "8d1a968cd0e389157584097aff7dccf1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.4.1-sources.jar",
          "url": "builder-8.4.1-sources.jar",
          "size": 281638,
          "sha512": "2ab86a5726ac440fc6b7986b1dcd2bde2f31383294a9aa95284ec80620c537018a789c7a1b80ab1ed12f8a35177a6a8fc51255e36c85ecab010502c9d690d6d7",
          "sha256": "c5700bef2fe01a8face80d07029d34f0730011c89f3e9867586c282c7e545b6d",
          "sha1": "cb36d6269be2c067ff82b8aaee2689fd68f91599",
          "md5": "4a3661fa8f4fef5c5352db937b259a07"
        }
      ]
    }
  ]
}
