{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.1.1.aar",
          "url": "runtime-1.1.1.aar",
          "size": 1899321,
          "sha512": "fcba19f27d67a59032ffca036d4851abf7727f877a68a137d6af3bfa9e92b943472257b9e8279acb606246017edeb4a75b4e96f9b87a133450d83d9b6396b8fc",
          "sha256": "e075b3e3952cb3775e7acc7ccdb8f2de777da76bd6d2ea2cc1f96d6f57b37763",
          "sha1": "2a327aba49259852213a0b505d3f14458b943a63",
          "md5": "f2e13a09a332a46c99cc4960034cebbf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.1.1.aar",
          "url": "runtime-1.1.1.aar",
          "size": 1899321,
          "sha512": "fcba19f27d67a59032ffca036d4851abf7727f877a68a137d6af3bfa9e92b943472257b9e8279acb606246017edeb4a75b4e96f9b87a133450d83d9b6396b8fc",
          "sha256": "e075b3e3952cb3775e7acc7ccdb8f2de777da76bd6d2ea2cc1f96d6f57b37763",
          "sha1": "2a327aba49259852213a0b505d3f14458b943a63",
          "md5": "f2e13a09a332a46c99cc4960034cebbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.1.1-sources.jar",
          "url": "runtime-1.1.1-sources.jar",
          "size": 261654,
          "sha512": "daaca5252afb22c0d6d57c4267fac484c1c74a46ff07563b0f8d0e2f43ca56ce26821649eef0adc2cc79b96200374009267cdbc3d898fc0de002a2e93d803332",
          "sha256": "5e643aef42937df0ba91ab9ce8c615cc206d56395b97d56fde04fb0ce7ed5c15",
          "sha1": "7ebc50c3f957ae73a45decd48282f25f8df77201",
          "md5": "ee1c13897f4edb29aee64de53a0ede7f"
        }
      ]
    }
  ]
}
